# Mainly useful for composer dependencies
.ssh_provision: &ssh_provision
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - echo "$SSH_ID_RSA" | tr -d "\r" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod -R 700 ~/.ssh
    - echo "$SSH_ID_RSA" | tr -d "\r" > ~/.ssh/id_rsa-ci-accor
    - bash ci/script/add-gitlab-token.bash composer.lock deployv2/environments.py .spbuilder.yml

# List and order of the stages
stages:
  - build
  - test
  - sonarqube-analysis
  - deploy

# -------------------- Build composer dependencies ------------------------
composer-build:
    stage: build
    image: meanbee/magento:7.0-cli
    tags:
        - docker-accor
    before_script:
        - apt update && apt install -y libzip-dev wget
        - docker-php-ext-install zip
        - *ssh_provision
    variables:
        COMPOSER_MEMORY_LIMIT: -1
    script:
        - sh ci/script/get-composer.sh
        - bin/composer self-update 1.10.17 #Fix composer version to lastest 1.x
        - composer install -q
    after_script:
        - ls -la
    cache:
        key:
            files:
                - composer.lock
        paths:
            - vendor
            - app/etc
            - generated
            - dev/tests/unit
            - app/autoload.php
            - app/bootstrap.php
            - app/functions.php
            - setup
            - lib
    artifacts:
        paths:
            - vendor
            - app/etc
            - generated
            - dev/tests/unit
            - app/autoload.php
            - app/bootstrap.php
            - app/functions.php
            - setup
            - lib
            - composer.lock
        expire_in: 1 week
    except:
        refs:
            - tags