variables:
  SONAR_SCANNER_VERSION: 3.3.0.1492

stages:
  - check

## ----- stage : check -----

sonar-mr:
  image:
    name: newtmitch/sonar-scanner:3.2-alpine
    entrypoint: ['']
  stage: check
  variables:
    SONAR_ANALYSIS_MODE: 'preview'
    SONAR_SCANNER_OPTS: '-Xmx2G'
  tags:
    - docker-accor
  script:
    - "sonar-scanner \
        -Dsonar.projectKey=accor \
        -Dsonar.host.url=https://sonar.pp.cicd.aws.smile.fr \
        -Dsonar.gitlab.api_version=v4 \
        -Dsonar.login=$SONAR_LOGIN \
        -Dsonar.analysis.mode=$SONAR_ANALYSIS_MODE \
        -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA \
        -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME \
        -Dsonar.gitlab.user_token=$GITLAB_USER_TOKEN \
        -Dsonar.gitlab.project_id=$CI_PROJECT_ID \
        -Dsonar.projectBaseDir=. \
        -Dsonar.profile=magento2 \
        -Dsonar.sources=app/code/Accor/ \
        -Dsonar.gitlab.only_issue_from_commit_line=true \
        -Dsonar.gitlab.max_major_issues_gate=0 \
        -Dsonar.gitlab.max_minor_issues_gate=0 \
        -Dsonar.sourceEncoding=UTF-8"
  only:
    refs:
        - merge_requests
    variables:
        - $CI_PROJECT_PATH == 'Accor/magento'

sonar_analyse:
  image:
    name: newtmitch/sonar-scanner:3.2-alpine
    entrypoint: ['']
  tags:
    - docker-accor
  stage: check
  variables:
    SONAR_ANALYSIS_MODE: 'publish'
  script:
    - "sonar-scanner \
        -Dsonar.projectKey=accor \
        -Dsonar.host.url=https://sonar.pp.cicd.aws.smile.fr \
        -Dsonar.gitlab.api_version=v4 \
        -Dsonar.login=$SONAR_LOGIN \
        -Dsonar.analysis.mode=$SONAR_ANALYSIS_MODE \
        -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA \
        -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME \
        -Dsonar.gitlab.project_id=$CI_PROJECT_ID \
        -Dsonar.gitlab.user_token=$GITLAB_USER_TOKEN \
        -Dsonar.projectBaseDir=. \
        -Dsonar.profile=magento2 \
        -Dsonar.sources=app/code/Accor/ \
        -Dsonar.sourceEncoding=UTF-8"
  only:
    refs:
        - merge_requests
    variables:
        - $CI_PROJECT_PATH == 'Accor/magento'
  when: manual